export default function () {
  return {
    scrolled: false,
    userMode: false,
    new_category_img: [
      { id: 0, img_src: require('../../assets/cat/1.png') },
      { id: 1, img_src: require('../../assets/cat/2.png') },
      { id: 2, img_src: require('../../assets/cat/3.png') },
      { id: 3, img_src: require('../../assets/cat/4.png') },
      { id: 4, img_src: require('../../assets/cat/5.png') },
      { id: 5, img_src: require('../../assets/cat/6.png') },
      { id: 6, img_src: require('../../assets/cat/7.png') },
      { id: 7, img_src: require('../../assets/cat/8.png') },
      { id: 8, img_src: require('../../assets/cat/9.png') },
      { id: 9, img_src: require('../../assets/cat/10.png') },
      { id: 10, img_src: require('../../assets/cat/11.png') },
      { id: 11, img_src: require('../../assets/cat/12.png') },
      { id: 12, img_src: require('../../assets/cat/13.png') },
      { id: 13, img_src: require('../../assets/cat/14.png') },
      { id: 14, img_src: require('../../assets/cat/15.png') },
      { id: 15, img_src: require('../../assets/cat/16.png') },
      { id: 16, img_src: require('../../assets/cat/17.png') },
      { id: 17, img_src: require('../../assets/cat/18.png') },
      { id: 18, img_src: require('../../assets/cat/19.png') },
      { id: 19, img_src: require('../../assets/cat/20.png') },
      { id: 20, img_src: require('../../assets/cat/21.png') },
      { id: 21, img_src: require('../../assets/cat/22.png') },
      { id: 22, img_src: require('../../assets/cat/23.png') },
      { id: 23, img_src: require('../../assets/cat/24.png') },
      { id: 24, img_src: require('../../assets/cat/25.png') },
      { id: 25, img_src: require('../../assets/cat/26.png') },
      { id: 26, img_src: require('../../assets/cat/27.png') },
      { id: 27, img_src: require('../../assets/cat/28.png') },
      { id: 28, img_src: require('../../assets/cat/29.png') },
      { id: 29, img_src: require('../../assets/cat/30.png') }
    ],
    category: [
      { id: 1, name: 'All', count: 0, img_src: require('../../assets/img/all.png') },
      { id: 2, name: 'Personal', count: 0, img_src: require('../../assets/img/personal.png') },
      { id: 3, name: 'Coding', count: 0, img_src: require('../../assets/img/code.png') },
      { id: 4, name: 'Bars', count: 0, img_src: require('../../assets/img/flex.png') },
      { id: 5, name: 'Health', count: 0, img_src: require('../../assets/img/health.png') },
      { id: 6, name: 'News', count: 0, img_src: require('../../assets/img/News.png') },
      { id: 7, name: 'Designs', count: 0, img_src: require('../../assets/img/paint.png') },
      { id: 8, name: 'Vacation', count: 0, img_src: require('../../assets/img/picnic.png') },
      { id: 9, name: 'Travels', count: 0, img_src: require('../../assets/img/Startup.png') },
      { id: 10, name: 'Sports', count: 0, img_src: require('../../assets/img/basketball.png') },
      { id: 11, name: 'Social Media', count: 0, img_src: require('../../assets/img/podcast.png') },
      { id: 12, name: 'Shopping', count: 0, img_src: require('../../assets/img/shop.png') },
      { id: 13, name: 'Work Outs', count: 0, img_src: require('../../assets/img/workout.png') }
    ],
    tasks: []
  }
}
